// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://siptvfxfvsihwgglozvu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpcHR2ZnhmdnNpaHdnZ2xvenZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ4NTI4ODQsImV4cCI6MjA1MDQyODg4NH0.jflw4Ygq8Eo6TdLtm1tayo5AN4HrP4zCdJ_2o1He_cE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);